// Auto-generated from UmmahAPI (https://www.ummahapi.com) -- free, no key.
// Serves as the offline fallback for the Duas feature. Categories normalized to app ids.

export type DuaCategory =
  'morning' |
  'evening' |
  'wudu' |
  'prayer' |
  'afterPrayer' |
  'sleeping' |
  'food' |
  'travel' |
  'home' |
  'enteringMosque' |
  'distress' |
  'forgiveness' |
  'illness' |
  'weather' |
  'knowledge' |
  'parents' |
  'guidance' |
  'gratitude' |
  'protection' |
  'dhikr' |
  'marriage' |
  'hajj' |
  'grief' |
  'children' |
  'business' |
  'nightPrayer' |
  'quran';
export type Dua = {
  id: string;
  category: DuaCategory;
  title: string;
  arabic: string;
  translation: string;
  source: string;
  transliteration?: string;
  repeat?: number;
};

export const DUA_CATEGORIES: DuaCategory[] = [
  'morning', 'evening', 'wudu', 'prayer', 'afterPrayer', 'sleeping', 'food', 'travel', 'home', 'enteringMosque', 'distress', 'forgiveness', 'illness', 'weather', 'knowledge', 'parents', 'guidance', 'gratitude', 'protection', 'dhikr', 'marriage', 'hajj', 'grief', 'children', 'business', 'nightPrayer', 'quran',
];

export const DUAS: Dua[] = [
  {
    id: "morning-1",
    category: "morning",
    title: "Morning Remembrance",
    arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    translation: "We have reached the morning and at this very time the whole kingdom belongs to Allah. All praise is due to Allah. None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise, and He is over all things omnipotent.",
    source: "Abu Dawud 4:317",
    transliteration: "Asbahna wa asbahal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadeer",
    repeat: 1,
  },
  {
    id: "morning-2",
    category: "morning",
    title: "Master of Forgiveness (Sayyid al-Istighfar)",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    translation: "O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favour upon me, and I acknowledge my sin, so forgive me, for verily none can forgive sins except You.",
    source: "Sahih Al-Bukhari 7:150",
    transliteration: "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana 'abduka, wa ana 'ala 'ahdika wa wa'dika mastata'tu, a'udhu bika min sharri ma sana'tu, abu'u laka bini'matika 'alayya, wa abu'u bidhanbi, faghfir li, fa innahu la yaghfirudh-dhunuba illa anta",
    repeat: 1,
  },
  {
    id: "morning-3",
    category: "morning",
    title: "Protection Morning Dua",
    arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    translation: "In the name of Allah, with whose name nothing can cause harm in the earth or in the heavens, and He is the All-Hearing, the All-Knowing.",
    source: "Abu Dawud 4:323, At-Tirmidhi 5:465",
    transliteration: "Bismillahilladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i wa huwas-sami'ul-'aleem",
    repeat: 3,
  },
  {
    id: "morning-46",
    category: "morning",
    title: "Morning Tasbih",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    translation: "Glory be to Allah and all praise is His. (Whoever says this 100 times in the morning and evening, no one will come on the Day of Resurrection with a better deed.)",
    source: "Sahih Al-Bukhari 8:412, Sahih Muslim 4:2071",
    transliteration: "SubhanAllahi wa bihamdih",
    repeat: 100,
  },
  {
    id: "morning-47",
    category: "morning",
    title: "Morning Protection with Al-Mu'awwidhat",
    arabic: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ",
    translation: "Recite Surah al-Ikhlas, al-Falaq, and an-Nas three times each morning for protection throughout the day.",
    source: "Abu Dawud 4:322, At-Tirmidhi 5:567",
    transliteration: "Qul a'udhu bi Rabbil-falaq (recite Surah al-Ikhlas, al-Falaq, an-Nas)",
    repeat: 3,
  },
  {
    id: "morning-48",
    category: "morning",
    title: "Dua for Good Morning",
    arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
    translation: "O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is the resurrection.",
    source: "Abu Dawud 4:317, At-Tirmidhi 5:466",
    transliteration: "Allahumma bika asbahna wa bika amsayna wa bika nahya wa bika namutu wa ilaykan-nushur",
    repeat: 1,
  },
  {
    id: "morning-49",
    category: "morning",
    title: "SubhanAllah al-Adheem Morning",
    arabic: "سُبْحَانَ اللَّهِ الْعَظِيمِ وَبِحَمْدِهِ",
    translation: "Glory be to Allah the Magnificent, and all praise is His. (A tree is planted in Paradise for whoever says this.)",
    source: "At-Tirmidhi, Al-Hakim",
    transliteration: "SubhanAllahil-'Adheem wa bihamdih",
    repeat: 1,
  },
  {
    id: "evening-4",
    category: "evening",
    title: "Evening Remembrance",
    arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    translation: "We have reached the evening and at this very time the whole kingdom belongs to Allah. All praise is due to Allah. None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise, and He is over all things omnipotent.",
    source: "Abu Dawud 4:317",
    transliteration: "Amsayna wa amsal-mulku lillah walhamdu lillah, la ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadeer",
    repeat: 1,
  },
  {
    id: "evening-5",
    category: "evening",
    title: "Evening Protection",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    source: "Sahih Muslim 4:2081",
    transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
    repeat: 3,
  },
  {
    id: "evening-50",
    category: "evening",
    title: "Evening Remembrance of Allah",
    arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ",
    translation: "O Allah, by You we enter the evening and by You we enter the morning, by You we live and by You we die, and to You is the return.",
    source: "Abu Dawud 4:317, At-Tirmidhi 5:466",
    transliteration: "Allahumma bika amsayna wa bika asbahna wa bika nahya wa bika namutu wa ilaykal-masir",
    repeat: 1,
  },
  {
    id: "evening-51",
    category: "evening",
    title: "Evening Seeking Forgiveness",
    arabic: "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ",
    translation: "I seek the forgiveness of Allah and I repent to Him.",
    source: "Sahih Al-Bukhari 8:319, Sahih Muslim 4:2075",
    transliteration: "Astaghfirullaha wa atubu ilayh",
    repeat: 100,
  },
  {
    id: "evening-52",
    category: "evening",
    title: "Evening Protection",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    source: "Sahih Muslim 4:2081",
    transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
    repeat: 3,
  },
  {
    id: "wudu-41",
    category: "wudu",
    title: "Before Wudu",
    arabic: "بِسْمِ اللَّهِ",
    translation: "In the name of Allah.",
    source: "Abu Dawud 1:73, At-Tirmidhi 1:5",
    transliteration: "Bismillah",
    repeat: 1,
  },
  {
    id: "wudu-42",
    category: "wudu",
    title: "After Wudu",
    arabic: "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
    translation: "I bear witness that there is no deity worthy of worship except Allah alone, with no partner, and I bear witness that Muhammad is His slave and messenger.",
    source: "Sahih Muslim 1:234",
    transliteration: "Ash-hadu an la ilaha illallahu wahdahu la shareeka lahu wa ash-hadu anna Muhammadan 'abduhu wa rasuluh",
    repeat: 1,
  },
  {
    id: "wudu-43",
    category: "wudu",
    title: "Complete After-Wudu Dua",
    arabic: "اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ",
    translation: "O Allah, make me among those who repent and make me among those who purify themselves.",
    source: "At-Tirmidhi 1:78",
    transliteration: "Allahumma-j'alni minat-tawwabina waj'alni minal-mutatahhirin",
    repeat: 1,
  },
  {
    id: "wudu-44",
    category: "wudu",
    title: "When Putting On Clothes",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    translation: "All praise is for Allah who clothed me with this and provided it for me without any might or power from myself.",
    source: "Abu Dawud 4:41, At-Tirmidhi 5:521",
    transliteration: "Alhamdu lillahilladhi kasani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
    repeat: 1,
  },
  {
    id: "wudu-45",
    category: "wudu",
    title: "When Undressing",
    arabic: "بِسْمِ اللَّهِ",
    translation: "In the name of Allah.",
    source: "Ibn Majah, At-Tirmidhi",
    transliteration: "Bismillah",
    repeat: 1,
  },
  {
    id: "prayer-6",
    category: "prayer",
    title: "Opening Supplication in Prayer",
    arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَى جَدُّكَ وَلَا إِلَهَ غَيْرُكَ",
    translation: "Glory be to You, O Allah, and all praises are due unto You, and blessed is Your name, and exalted is Your majesty, and there is no deity worthy of worship except You.",
    source: "Abu Dawud, At-Tirmidhi, An-Nasai",
    transliteration: "Subhanakallahumma wa bihamdika wa tabarakasmuka wa ta'ala jadduka wa la ilaha ghairuk",
    repeat: 1,
  },
  {
    id: "prayer-7",
    category: "prayer",
    title: "Between Sujud (Prostrations)",
    arabic: "رَبِّ اغْفِرْ لِي رَبِّ اغْفِرْ لِي",
    translation: "My Lord, forgive me. My Lord, forgive me.",
    source: "Abu Dawud 1:231",
    transliteration: "Rabbighfir li, Rabbighfir li",
    repeat: 1,
  },
  {
    id: "prayer-8",
    category: "prayer",
    title: "Dua in Sujud",
    arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَى",
    translation: "Glory is to my Lord, the Most High.",
    source: "Sahih Muslim",
    transliteration: "Subhana Rabbiyal-A'la",
    repeat: 3,
  },
  {
    id: "prayer-53",
    category: "prayer",
    title: "Dua in Ruku",
    arabic: "سُبْحَانَ رَبِّيَ الْعَظِيمِ",
    translation: "Glory is to my Lord, the Most Great.",
    source: "Abu Dawud 1:230, Sahih Muslim",
    transliteration: "Subhana Rabbiyal-'Adheem",
    repeat: 3,
  },
  {
    id: "prayer-54",
    category: "prayer",
    title: "Rising from Ruku",
    arabic: "رَبَّنَا وَلَكَ الْحَمْدُ حَمْدًا كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ",
    translation: "Our Lord, and to You is all praise, abundant, pure and blessed praise.",
    source: "Sahih Al-Bukhari 1:773",
    transliteration: "Rabbana wa lakal-hamdu hamdan kathiran tayyiban mubarakan fih",
    repeat: 1,
  },
  {
    id: "prayer-55",
    category: "prayer",
    title: "Tashahud",
    arabic: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
    translation: "All greetings, prayers and good things are for Allah. Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous servants of Allah. I bear witness that there is no deity worthy of worship except Allah, and I bear witness that Muhammad is His slave and messenger.",
    source: "Sahih Al-Bukhari 1:831, Sahih Muslim 1:402",
    transliteration: "At-tahiyyatu lillahi was-salawatu wat-tayyibat, as-salamu 'alayka ayyuhan-nabiyyu wa rahmatullahi wa barakatuh, as-salamu 'alayna wa 'ala 'ibadillahis-salihin, ash-hadu an la ilaha illallah wa ash-hadu anna Muhammadan 'abduhu wa rasuluh",
    repeat: 1,
  },
  {
    id: "prayer-56",
    category: "prayer",
    title: "Salawat (Ibrahimiyya) in Prayer",
    arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ",
    translation: "O Allah, send prayers upon Muhammad and the family of Muhammad, as You sent prayers upon Ibrahim and the family of Ibrahim. You are indeed Praiseworthy, Glorious. O Allah, bless Muhammad and the family of Muhammad, as You blessed Ibrahim and the family of Ibrahim. You are indeed Praiseworthy, Glorious.",
    source: "Sahih Al-Bukhari 4:589, Sahih Muslim 1:406",
    transliteration: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammadin kama sallayta 'ala Ibrahima wa 'ala ali Ibrahima innaka Hamidun Majid, Allahumma barik 'ala Muhammadin wa 'ala ali Muhammadin kama barakta 'ala Ibrahima wa 'ala ali Ibrahima innaka Hamidun Majid",
    repeat: 1,
  },
  {
    id: "prayer-57",
    category: "prayer",
    title: "Dua Before Salam (After Tashahud)",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ وَمِنْ عَذَابِ النَّارِ وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ وَمِنْ شَرِّ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ",
    translation: "O Allah, I seek refuge in You from the punishment of the grave, from the punishment of the fire, from the trials of life and death, and from the evil of the trial of the False Messiah.",
    source: "Sahih Al-Bukhari 2:102, Sahih Muslim 1:590",
    transliteration: "Allahumma inni a'udhu bika min 'adhabil-qabri wa min 'adhabin-nar, wa min fitnatil-mahya wal-mamat, wa min sharri fitnatil-masihid-dajjal",
    repeat: 1,
  },
  {
    id: "afterPrayer-9",
    category: "afterPrayer",
    title: "Istighfar After Prayer",
    arabic: "أَسْتَغْفِرُ اللَّهَ",
    translation: "I seek forgiveness from Allah.",
    source: "Sahih Muslim 1:414",
    transliteration: "Astaghfirullah",
    repeat: 3,
  },
  {
    id: "afterPrayer-10",
    category: "afterPrayer",
    title: "SubhanAllah After Prayer",
    arabic: "سُبْحَانَ اللَّهِ",
    translation: "Glory be to Allah.",
    source: "Sahih Muslim 1:418",
    transliteration: "SubhanAllah",
    repeat: 33,
  },
  {
    id: "afterPrayer-11",
    category: "afterPrayer",
    title: "Alhamdulillah After Prayer",
    arabic: "الْحَمْدُ لِلَّهِ",
    translation: "All praise is due to Allah.",
    source: "Sahih Muslim 1:418",
    transliteration: "Alhamdulillah",
    repeat: 33,
  },
  {
    id: "afterPrayer-12",
    category: "afterPrayer",
    title: "Allahu Akbar After Prayer",
    arabic: "اللَّهُ أَكْبَرُ",
    translation: "Allah is the Greatest.",
    source: "Sahih Muslim 1:418",
    transliteration: "Allahu Akbar",
    repeat: 33,
  },
  {
    id: "afterPrayer-13",
    category: "afterPrayer",
    title: "Ayat al-Kursi After Prayer",
    arabic: "اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ",
    translation: "Allah! There is no deity except Him, the Ever-Living, the Sustainer of existence... (full Ayat al-Kursi, Quran 2:255)",
    source: "An-Nasai, Al-Kubra",
    transliteration: "Allahu la ilaha illa Huwal-Hayyul-Qayyum...",
    repeat: 1,
  },
  {
    id: "afterPrayer-58",
    category: "afterPrayer",
    title: "La ilaha illallah 10 Times After Fajr and Maghrib",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ يُحْيِي وَيُمِيتُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    translation: "None has the right to be worshipped except Allah, alone, with no partner. To Him belongs all sovereignty and all praise. He gives life and causes death, and He is over all things omnipotent.",
    source: "At-Tirmidhi 5:515",
    transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamdu yuhyi wa yumitu wa huwa 'ala kulli shay'in qadir",
    repeat: 10,
  },
  {
    id: "afterPrayer-59",
    category: "afterPrayer",
    title: "Dua for Best of This World and Next",
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    translation: "Our Lord, give us good in this world and good in the next, and protect us from the punishment of the Fire.",
    source: "Quran 2:201, Sahih Al-Bukhari 8:95",
    transliteration: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina 'adhaban-nar",
    repeat: 1,
  },
  {
    id: "afterPrayer-60",
    category: "afterPrayer",
    title: "Seeking Refuge After Prayer",
    arabic: "اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
    translation: "O Allah, help me to remember You, to be grateful to You, and to worship You in an excellent manner.",
    source: "Abu Dawud 2:86, An-Nasai",
    transliteration: "Allahumma a'inni 'ala dhikrika wa shukrika wa husni 'ibadatik",
    repeat: 1,
  },
  {
    id: "sleeping-14",
    category: "sleeping",
    title: "Before Sleeping",
    arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    translation: "In Your name, O Allah, I die and I live.",
    source: "Sahih Al-Bukhari 11:113",
    transliteration: "Bismika Allahumma amutu wa ahya",
    repeat: 1,
  },
  {
    id: "sleeping-15",
    category: "sleeping",
    title: "Upon Waking Up",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    translation: "All praise is for Allah who gave us life after having taken it from us, and unto Him is the resurrection.",
    source: "Sahih Al-Bukhari 11:113",
    transliteration: "Alhamdu lillahilladhi ahyana ba'da ma amatana wa ilaihin-nushur",
    repeat: 1,
  },
  {
    id: "sleeping-61",
    category: "sleeping",
    title: "Reciting Al-Mu'awwidhat Before Sleep",
    arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ",
    translation: "Recite Surah al-Ikhlas, al-Falaq, and an-Nas three times, blow into cupped hands, then wipe over the body starting with the head and face.",
    source: "Sahih Al-Bukhari 6:536",
    transliteration: "Qul Huwallahu Ahad (recite Surah al-Ikhlas, al-Falaq, an-Nas — blow into cupped hands and wipe over body)",
    repeat: 3,
  },
  {
    id: "sleeping-62",
    category: "sleeping",
    title: "Dua for a Bad Dream",
    arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
    translation: "I seek refuge in Allah from the accursed devil. (Spit lightly to the left three times and turn over to the other side upon seeing a bad dream.)",
    source: "Sahih Muslim 4:1772",
    transliteration: "A'udhu billahi minash-shaytanir-rajeem",
    repeat: 3,
  },
  {
    id: "sleeping-63",
    category: "sleeping",
    title: "Upon Waking at Night",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    translation: "None has the right to be worshipped except Allah, alone, with no partner. To Him belongs all sovereignty and all praise, and He is over all things omnipotent. Glory be to Allah, all praise is due to Allah, none has the right to be worshipped except Allah, Allah is the Greatest, and there is no might or power except with Allah.",
    source: "Sahih Al-Bukhari 2:323",
    transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadir, SubhanAllahi wal-hamdu lillahi wa la ilaha illallahu wallahu akbar wa la hawla wa la quwwata illa billah",
    repeat: 1,
  },
  {
    id: "sleeping-64",
    category: "sleeping",
    title: "Upon Seeing a Good Dream",
    arabic: "الْحَمْدُ لِلَّهِ",
    translation: "All praise is due to Allah. (Upon seeing a good dream, praise Allah and tell those you love. Do not tell it to those who may be envious.)",
    source: "Sahih Al-Bukhari 9:119",
    transliteration: "Alhamdulillah",
    repeat: 1,
  },
  {
    id: "food-16",
    category: "food",
    title: "Before Eating",
    arabic: "بِسْمِ اللَّهِ",
    translation: "In the name of Allah.",
    source: "Abu Dawud 3:347, At-Tirmidhi 4:288",
    transliteration: "Bismillah",
    repeat: 1,
  },
  {
    id: "food-17",
    category: "food",
    title: "After Eating",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    translation: "All praise is for Allah who fed me this and provided it for me without any might or power from myself.",
    source: "Abu Dawud, At-Tirmidhi, Ibn Majah",
    transliteration: "Alhamdu lillahilladhi at'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
    repeat: 1,
  },
  {
    id: "food-18",
    category: "food",
    title: "Forgetting Bismillah Before Eating",
    arabic: "بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ",
    translation: "In the name of Allah at its beginning and at its end.",
    source: "Abu Dawud 3:347, At-Tirmidhi 4:288",
    transliteration: "Bismillahi awwalahu wa akhirah",
    repeat: 1,
  },
  {
    id: "food-65",
    category: "food",
    title: "Dua at Iftar",
    arabic: "اللَّهُمَّ لَكَ صُمْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ",
    translation: "O Allah, for You I have fasted and upon Your provision I have broken my fast.",
    source: "Abu Dawud 2:306",
    transliteration: "Allahumma laka sumtu wa 'ala rizqika aftartu",
    repeat: 1,
  },
  {
    id: "food-66",
    category: "food",
    title: "Dua When Invited to Eat",
    arabic: "اللَّهُمَّ أَطْعِمْ مَنْ أَطْعَمَنِي وَاسْقِ مَنْ سَقَانِي",
    translation: "O Allah, feed the one who has fed me, and give drink to the one who has given me drink.",
    source: "Sahih Muslim 3:126",
    transliteration: "Allahumma at'im man at'amani wasqi man saqani",
    repeat: 1,
  },
  {
    id: "food-67",
    category: "food",
    title: "Dua for the Host",
    arabic: "أَفْطَرَ عِنْدَكُمُ الصَّائِمُونَ وَأَكَلَ طَعَامَكُمُ الْأَبْرَارُ وَصَلَّتْ عَلَيْكُمُ الْمَلَائِكَةُ",
    translation: "May the fasting break their fast with you, may the righteous eat your food, and may the angels send blessings upon you.",
    source: "Abu Dawud 3:367, Ibn Majah 1:556",
    transliteration: "Aftara 'indakumus-sa'imuna wa akala ta'amakumul-abrar wa sallat 'alaykumul-mala'ikah",
    repeat: 1,
  },
  {
    id: "travel-19",
    category: "travel",
    title: "Travel Dua",
    arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ",
    translation: "Glory to Him who has subjected this to us, and we could never have it by our efforts, and verily to our Lord we shall return.",
    source: "Quran 43:13-14, Sahih Muslim 2:978",
    transliteration: "Subhanal-ladhi sakh-khara lana hadha wa ma kunna lahu muqrinin wa inna ila Rabbina lamunqalibun",
    repeat: 1,
  },
  {
    id: "travel-20",
    category: "travel",
    title: "Entering a Town or City",
    arabic: "اللَّهُمَّ رَبَّ السَّمَوَاتِ السَّبْعِ وَمَا أَظْلَلْنَ وَرَبَّ الْأَرَضِينَ السَّبْعِ وَمَا أَقْلَلْنَ وَرَبَّ الشَّيَاطِينِ وَمَا أَضْلَلْنَ وَرَبَّ الرِّيَاحِ وَمَا ذَرَيْنَ أَسْأَلُكَ خَيْرَ هَذِهِ الْقَرْيَةِ وَخَيْرَ أَهْلِهَا وَخَيْرَ مَا فِيهَا وَأَعُوذُ بِكَ مِنْ شَرِّهَا وَشَرِّ أَهْلِهَا وَشَرِّ مَا فِيهَا",
    translation: "O Allah, Lord of the seven heavens and all that they envelop, Lord of the seven earths and all that they carry, Lord of the devils and all whom they misguide, Lord of the winds and all whom they whisk away. I ask You for the goodness of this town, the goodness of its people and the goodness of what is in it. I seek refuge in You from its evil, the evil of its people and the evil of what is in it.",
    source: "Al-Hakim 2:100, An-Nasai",
    transliteration: "Allahumma Rabbas-samawatis-sab'i wa ma adhlalna, wa Rabbal-aradeenas-sab'i wa ma aqlalna, wa Rabbash-shayateeni wa ma adlalna, wa Rabbar-riyahi wa ma dharayna, as'aluka khayra hadhihil-qaryati wa khayra ahliha wa khayra ma fiha, wa a'udhu bika min sharriha wa sharri ahliha wa sharri ma fiha",
    repeat: 1,
  },
  {
    id: "travel-68",
    category: "travel",
    title: "Stopping at a Place",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created. (Whoever says this when stopping at a place will not be harmed until he leaves.)",
    source: "Sahih Muslim 4:2080",
    transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
    repeat: 1,
  },
  {
    id: "travel-69",
    category: "travel",
    title: "Returning From Travel",
    arabic: "آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ",
    translation: "We return, repent, worship and praise our Lord.",
    source: "Sahih Al-Bukhari 2:995, Sahih Muslim 2:980",
    transliteration: "Ayibuna ta'ibuna 'abiduna li Rabbina hamidun",
    repeat: 1,
  },
  {
    id: "travel-70",
    category: "travel",
    title: "Dua for the Traveler (From Family at Home)",
    arabic: "أَسْتَوْدِعُ اللَّهَ دِينَكَ وَأَمَانَتَكَ وَخَوَاتِيمَ عَمَلِكَ",
    translation: "I entrust Allah with your religion, your trust, and the ends of your deeds.",
    source: "Abu Dawud 3:74, At-Tirmidhi 5:499",
    transliteration: "Astawdi'ullah dinaka wa amanataka wa khawatima 'amalik",
    repeat: 1,
  },
  {
    id: "travel-71",
    category: "travel",
    title: "Dua at the Beginning of a Journey",
    arabic: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى وَمِنَ الْعَمَلِ مَا تَرْضَى",
    translation: "O Allah, we ask You on this journey of ours for righteousness and piety, and for deeds that are pleasing to You.",
    source: "Sahih Muslim 2:978",
    transliteration: "Allahumma inna nas'aluka fi safarina hadhal-birra wat-taqwa wa minal-'amali ma tarda",
    repeat: 1,
  },
  {
    id: "home-21",
    category: "home",
    title: "Leaving the Home",
    arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    translation: "In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.",
    source: "Abu Dawud 4:325, At-Tirmidhi 5:490",
    transliteration: "Bismillah, tawakkaltu 'alallah, wa la hawla wa la quwwata illa billah",
    repeat: 1,
  },
  {
    id: "home-22",
    category: "home",
    title: "Entering the Home",
    arabic: "بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا",
    translation: "In the name of Allah we enter, in the name of Allah we leave, and upon our Lord we place our trust.",
    source: "Abu Dawud 4:325",
    transliteration: "Bismillahi walajna, wa bismillahi kharajna, wa 'ala Allahi Rabbina tawakkalna",
    repeat: 1,
  },
  {
    id: "enteringMosque-23",
    category: "enteringMosque",
    title: "Entering the Masjid",
    arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    translation: "O Allah, open for me the doors of Your mercy.",
    source: "Sahih Muslim 1:494",
    transliteration: "Allahummaf-tah li abwaba rahmatik",
    repeat: 1,
  },
  {
    id: "enteringMosque-24",
    category: "enteringMosque",
    title: "Leaving the Masjid",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
    translation: "O Allah, I ask You from Your favour.",
    source: "Sahih Muslim 1:494",
    transliteration: "Allahumma inni as'aluka min fadlik",
    repeat: 1,
  },
  {
    id: "enteringMosque-72",
    category: "enteringMosque",
    title: "Dua After Adhan",
    arabic: "اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ",
    translation: "O Allah, Lord of this perfect call and the prayer that is to come, grant Muhammad the privilege and the distinction, and raise him to a praised station that You have promised him.",
    source: "Sahih Al-Bukhari 1:614",
    transliteration: "Allahumma Rabba hadhihid-da'watit-tammati was-salatil-qa'ima, ati Muhammadanil-wasilata wal-fadilata wab'ath-hu maqaman mahmudanil-ladhi wa'adtah",
    repeat: 1,
  },
  {
    id: "enteringMosque-73",
    category: "enteringMosque",
    title: "Dua While Waiting for Prayer",
    arabic: "اللَّهُمَّ اغْفِرْ لِي ذُنُوبِي وَافْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    translation: "O Allah, forgive my sins and open for me the doors of Your mercy.",
    source: "At-Tirmidhi, Ibn Majah",
    transliteration: "Allahummaghfir li dhunubi waftah li abwaba rahmatik",
    repeat: 1,
  },
  {
    id: "distress-25",
    category: "distress",
    title: "Dua for Distress",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ لَا إِلَهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ لَا إِلَهَ إِلَّا اللَّهُ رَبُّ السَّمَوَاتِ وَرَبُّ الْأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ",
    translation: "None has the right to be worshipped except Allah, the Mighty, the Forbearing. None has the right to be worshipped except Allah, Lord of the magnificent throne. None has the right to be worshipped except Allah, Lord of the heavens, Lord of the earth, and Lord of the noble throne.",
    source: "Sahih Al-Bukhari 8:154, Sahih Muslim 4:2092",
    transliteration: "La ilaha illallahul-'Adheemul-Haleem, la ilaha illallahu Rabbul-'Arshil-'Adheem, la ilaha illallahu Rabbus-samawati wa Rabbul-ardi wa Rabbul-'Arshil-Kareem",
    repeat: 1,
  },
  {
    id: "distress-26",
    category: "distress",
    title: "Dua of Yunus (Jonah)",
    arabic: "لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",
    translation: "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.",
    source: "Quran 21:87, At-Tirmidhi",
    transliteration: "La ilaha illa anta subhanaka inni kuntu minadh-dhalimeen",
    repeat: 1,
  },
  {
    id: "distress-27",
    category: "distress",
    title: "When Anxious or Worried",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ",
    translation: "O Allah, I seek refuge in You from worry and grief, from helplessness and laziness, from cowardice and miserliness, from being overwhelmed by debt and overpowered by men.",
    source: "Sahih Al-Bukhari 7:158",
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazani, wa a'udhu bika minal-'ajzi wal-kasali, wa a'udhu bika minal-jubni wal-bukhli, wa a'udhu bika min ghalabatid-dayni wa qahrir-rijal",
    repeat: 1,
  },
  {
    id: "distress-74",
    category: "distress",
    title: "Dua of Prophet Ayyub (Job)",
    arabic: "رَبِّ أَنِّي مَسَّنِيَ الضُّرُّ وَأَنْتَ أَرْحَمُ الرَّاحِمِينَ",
    translation: "My Lord, adversity has touched me, and You are the Most Merciful of the merciful.",
    source: "Quran 21:83",
    transliteration: "Rabbi anni massaniyad-durru wa anta arhamur-rahimin",
    repeat: 1,
  },
  {
    id: "distress-75",
    category: "distress",
    title: "Hasbunallah",
    arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
    translation: "Allah is sufficient for us and He is the best disposer of affairs.",
    source: "Quran 3:173, Sahih Al-Bukhari 8:69",
    transliteration: "Hasbunallahu wa ni'mal-wakil",
    repeat: 1,
  },
  {
    id: "distress-76",
    category: "distress",
    title: "La Hawla Wa La Quwwata",
    arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    translation: "There is no might nor power except with Allah. (It is a treasure from the treasures of Paradise.)",
    source: "Sahih Al-Bukhari 7:158, Sahih Muslim 4:2076",
    transliteration: "La hawla wa la quwwata illa billah",
    repeat: 1,
  },
  {
    id: "distress-77",
    category: "distress",
    title: "Dua for Ease in Difficulty",
    arabic: "اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا",
    translation: "O Allah, there is no ease except in that which You have made easy, and You make the difficult easy if You wish.",
    source: "Ibn Hibban, Ibn As-Sunni",
    transliteration: "Allahumma la sahla illa ma ja'altahu sahla wa anta taj'alul-hazna idha shi'ta sahla",
    repeat: 1,
  },
  {
    id: "forgiveness-28",
    category: "forgiveness",
    title: "Seeking Forgiveness",
    arabic: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
    translation: "I seek the forgiveness of Allah the Mighty, whom there is none worthy of worship except Him, the Living, the Sustainer, and I repent to Him.",
    source: "Abu Dawud, At-Tirmidhi",
    transliteration: "Astaghfirullaha al-'Adheem alladhi la ilaha illa Huwal-Hayyul-Qayyum wa atubu ilayh",
    repeat: 3,
  },
  {
    id: "forgiveness-29",
    category: "forgiveness",
    title: "Comprehensive Forgiveness",
    arabic: "رَبَّنَا ظَلَمْنَا أَنْفُسَنَا وَإِنْ لَمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ",
    translation: "Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.",
    source: "Quran 7:23",
    transliteration: "Rabbana dhalamna anfusana wa in lam taghfir lana wa tarhamna lanakoonanna minal-khasireen",
    repeat: 1,
  },
  {
    id: "forgiveness-78",
    category: "forgiveness",
    title: "Dua for Laylat al-Qadr",
    arabic: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي",
    translation: "O Allah, You are Pardoning and You love to pardon, so pardon me.",
    source: "At-Tirmidhi 5:534, Ibn Majah 2:1265",
    transliteration: "Allahumma innaka 'afuwwun tuhibbul-'afwa fa'fu 'anni",
    repeat: 1,
  },
  {
    id: "forgiveness-79",
    category: "forgiveness",
    title: "Dua Between Adhan and Iqamah",
    arabic: "اللَّهُمَّ اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ",
    translation: "O Allah, forgive me and my parents and the believing men and believing women.",
    source: "Quran 71:28, Ibn Majah",
    transliteration: "Allahummaghfir li wa liwali dayya wa lil-mu'minina wal-mu'minat",
    repeat: 1,
  },
  {
    id: "forgiveness-80",
    category: "forgiveness",
    title: "Dua of Adam and Hawwa",
    arabic: "رَبَّنَا ظَلَمْنَا أَنْفُسَنَا وَإِنْ لَمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ",
    translation: "Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.",
    source: "Quran 7:23",
    transliteration: "Rabbana dhalamna anfusana wa in lam taghfir lana wa tarhamna lanakoonanna minal-khasireen",
    repeat: 1,
  },
  {
    id: "illness-30",
    category: "illness",
    title: "Visiting the Sick",
    arabic: "لَا بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّهُ",
    translation: "No harm, it is a purification, if Allah wills.",
    source: "Sahih Al-Bukhari 7:372",
    transliteration: "La ba'sa tahurun insha'Allah",
    repeat: 1,
  },
  {
    id: "illness-31",
    category: "illness",
    title: "Dua for Healing",
    arabic: "اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ اشْفِ أَنْتَ الشَّافِي لَا شِفَاءَ إِلَّا شِفَاؤُكَ شِفَاءً لَا يُغَادِرُ سَقَمًا",
    translation: "O Allah, Lord of mankind, remove the affliction. Cure, for You are the One who cures. There is no cure except Your cure, a cure that leaves no illness behind.",
    source: "Sahih Al-Bukhari 7:379, Sahih Muslim",
    transliteration: "Allahumma Rabban-nasi, adhibil-ba'sa, ishfi antash-Shafi, la shifa'a illa shifa'uka, shifa'an la yughadiru saqama",
    repeat: 1,
  },
  {
    id: "illness-81",
    category: "illness",
    title: "Ruqyah: Bismillah x3, A'udhu x7",
    arabic: "أَعُوذُ بِاللَّهِ وَقُدْرَتِهِ مِنْ شَرِّ مَا أَجِدُ وَأُحَاذِرُ",
    translation: "I seek refuge in Allah and His power from the evil of what I feel and what I am wary of. (Place hand on the area of pain and say Bismillah three times, then this dua seven times.)",
    source: "Sahih Muslim 4:1728",
    transliteration: "A'udhu billahi wa qudratihi min sharri ma ajidu wa uhādhir",
    repeat: 7,
  },
  {
    id: "illness-82",
    category: "illness",
    title: "Dua for Someone Who Is Ill",
    arabic: "أَسْأَلُ اللَّهَ الْعَظِيمَ رَبَّ الْعَرْشِ الْعَظِيمِ أَنْ يَشْفِيَكَ",
    translation: "I ask Allah the Magnificent, Lord of the Magnificent Throne, to cure you.",
    source: "Abu Dawud 3:187, At-Tirmidhi 2:210",
    transliteration: "As'alullahil-'Adhima Rabbal-'Arshil-'Adhimi an yashfiyak",
    repeat: 7,
  },
  {
    id: "illness-83",
    category: "illness",
    title: "Dua for Pain in the Body",
    arabic: "بِسْمِ اللَّهِ بِسْمِ اللَّهِ بِسْمِ اللَّهِ",
    translation: "In the name of Allah (3 times), then: I seek refuge in Allah and His power from the evil of what I feel and what I am wary of (7 times).",
    source: "Sahih Muslim 4:1728",
    transliteration: "Bismillah (x3), then: A'udhu billahi wa qudratihi min sharri ma ajidu wa uhādhir (x7)",
    repeat: 1,
  },
  {
    id: "weather-32",
    category: "weather",
    title: "When It Rains",
    arabic: "اللَّهُمَّ صَيِّبًا نَافِعًا",
    translation: "O Allah, let it be a beneficial rain.",
    source: "Sahih Al-Bukhari",
    transliteration: "Allahumma sayyiban nafi'a",
    repeat: 1,
  },
  {
    id: "weather-33",
    category: "weather",
    title: "After Rain",
    arabic: "مُطِرْنَا بِفَضْلِ اللَّهِ وَرَحْمَتِهِ",
    translation: "We have been given rain by the grace and mercy of Allah.",
    source: "Sahih Al-Bukhari 1:147, Sahih Muslim 1:58",
    transliteration: "Mutirna bifadlillahi wa rahmatihi",
    repeat: 1,
  },
  {
    id: "weather-34",
    category: "weather",
    title: "During Thunder",
    arabic: "سُبْحَانَ الَّذِي يُسَبِّحُ الرَّعْدُ بِحَمْدِهِ وَالْمَلَائِكَةُ مِنْ خِيفَتِهِ",
    translation: "Glory be to Him whom the thunder glorifies with His praise, and the angels out of fear of Him.",
    source: "Al-Muwatta' 2:992",
    transliteration: "Subhanal-ladhi yusabbihur-ra'du bihamdihi wal-mala'ikatu min khifatihi",
    repeat: 1,
  },
  {
    id: "knowledge-35",
    category: "knowledge",
    title: "Increase in Knowledge",
    arabic: "رَبِّ زِدْنِي عِلْمًا",
    translation: "My Lord, increase me in knowledge.",
    source: "Quran 20:114",
    transliteration: "Rabbi zidni 'ilma",
    repeat: 1,
  },
  {
    id: "knowledge-84",
    category: "knowledge",
    title: "Dua for Beneficial Knowledge",
    arabic: "اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنْفَعُنِي وَزِدْنِي عِلْمًا",
    translation: "O Allah, benefit me with what You have taught me, teach me what will benefit me, and increase me in knowledge.",
    source: "At-Tirmidhi 5:742, Ibn Majah 1:92",
    transliteration: "Allahumman-fa'ni bima 'allamtani wa 'allimni ma yanfa'uni wa zidni 'ilma",
    repeat: 1,
  },
  {
    id: "knowledge-85",
    category: "knowledge",
    title: "Seeking Refuge from Useless Knowledge",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عِلْمٍ لَا يَنْفَعُ وَمِنْ قَلْبٍ لَا يَخْشَعُ وَمِنْ نَفْسٍ لَا تَشْبَعُ وَمِنْ دَعْوَةٍ لَا يُسْتَجَابُ لَهَا",
    translation: "O Allah, I seek refuge in You from knowledge that does not benefit, from a heart that does not fear, from a soul that is not satisfied, and from a supplication that is not answered.",
    source: "Sahih Muslim 4:2088, Abu Dawud",
    transliteration: "Allahumma inni a'udhu bika min 'ilmin la yanfa'u wa min qalbin la yakhsha'u wa min nafsin la tashba'u wa min da'watin la yustajabu laha",
    repeat: 1,
  },
  {
    id: "parents-36",
    category: "parents",
    title: "Dua for Parents",
    arabic: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    translation: "My Lord, have mercy upon them as they brought me up when I was small.",
    source: "Quran 17:24",
    transliteration: "Rabbir-hamhuma kama rabbayani sagheera",
    repeat: 1,
  },
  {
    id: "parents-86",
    category: "parents",
    title: "Dua for Deceased Parents",
    arabic: "اللَّهُمَّ اغْفِرْ لِي وَلِوَالِدَيَّ وَارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    translation: "O Allah, forgive me and my parents and have mercy on them as they raised me when I was young.",
    source: "Quran 17:24, Abu Dawud",
    transliteration: "Allahummaghfir li wa liwali dayya warhamhuma kama rabbayani saghira",
    repeat: 1,
  },
  {
    id: "parents-87",
    category: "parents",
    title: "Dua for Living Parents' Well-being",
    arabic: "رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَلِمَنْ دَخَلَ بَيْتِيَ مُؤْمِنًا وَلِلْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ",
    translation: "My Lord, forgive me, my parents, whoever enters my house as a believer, and all believing men and women.",
    source: "Quran 71:28",
    transliteration: "Rabbighfir li wa liwali dayya wa liman dakhala bayti mu'minan wa lil-mu'minina wal-mu'minat",
    repeat: 1,
  },
  {
    id: "guidance-37",
    category: "guidance",
    title: "Istikhara (Seeking Guidance)",
    arabic: "اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ وَتَعْلَمُ وَلَا أَعْلَمُ وَأَنْتَ عَلَّامُ الْغُيُوبِ",
    translation: "O Allah, I seek Your guidance by virtue of Your knowledge, and I seek ability by virtue of Your power, and I ask You of Your great bounty. You have power and I have none. And You know and I know not. You are the Knower of hidden things.",
    source: "Sahih Al-Bukhari 2:263",
    transliteration: "Allahumma inni astakheeruka bi'ilmika wa astaqdiruka biqudratika wa as'aluka min fadlikal-'adheem, fa innaka taqdiru wa la aqdir, wa ta'lamu wa la a'lam, wa anta 'allamul-ghuyub",
    repeat: 1,
  },
  {
    id: "guidance-88",
    category: "guidance",
    title: "Dua for Steadfastness on the Truth",
    arabic: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ",
    translation: "O Turner of hearts, keep my heart firm upon Your religion.",
    source: "At-Tirmidhi 4:447, Ahmad",
    transliteration: "Ya Muqallibal-qulub, thabbit qalbi 'ala dinik",
    repeat: 1,
  },
  {
    id: "guidance-89",
    category: "guidance",
    title: "Dua for Good Character",
    arabic: "اللَّهُمَّ أَحْسَنْتَ خَلْقِي فَأَحْسِنْ خُلُقِي",
    translation: "O Allah, You have made my physical form beautiful, so beautify my character too.",
    source: "Ahmad, Ibn Hibban",
    transliteration: "Allahumma ahsanta khalqi fa-ahsin khuluqi",
    repeat: 1,
  },
  {
    id: "gratitude-38",
    category: "gratitude",
    title: "Thanking Allah",
    arabic: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
    translation: "All praise is due to Allah, Lord of all the worlds.",
    source: "Quran 1:2",
    transliteration: "Alhamdu lillahi Rabbil-'alameen",
    repeat: 1,
  },
  {
    id: "gratitude-90",
    category: "gratitude",
    title: "Dua of Prophet Sulayman for Gratitude",
    arabic: "رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَى وَالِدَيَّ وَأَنْ أَعْمَلَ صَالِحًا تَرْضَاهُ",
    translation: "My Lord, enable me to be grateful for Your favor which You have bestowed upon me and upon my parents, and to work righteousness of which You will approve.",
    source: "Quran 27:19, 46:15",
    transliteration: "Rabbi awzi'ni an ashkura ni'matakal-lati an'amta 'alayya wa 'ala walidayya wa an a'mala salihan tardah",
    repeat: 1,
  },
  {
    id: "gratitude-91",
    category: "gratitude",
    title: "Praising Allah Upon Receiving a Blessing",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ",
    translation: "All praise is for Allah, by whose blessing all good things are completed.",
    source: "Ibn Majah 2:1265, Al-Hakim",
    transliteration: "Alhamdu lillahilladhi bi-ni'matihi tatimus-salihat",
    repeat: 1,
  },
  {
    id: "protection-39",
    category: "protection",
    title: "Seeking Protection from Evil Eye",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ",
    translation: "I seek refuge in the perfect words of Allah from every devil and every poisonous reptile, and from every evil eye.",
    source: "Sahih Al-Bukhari 4:119",
    transliteration: "A'udhu bikalimatillahit-tammati min kulli shaytanin wa hammatin wa min kulli 'aynin lammah",
    repeat: 1,
  },
  {
    id: "protection-40",
    category: "protection",
    title: "General Protection",
    arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    translation: "In the name of Allah, with whose name nothing can cause harm in the earth or in the heavens, and He is the All-Hearing, the All-Knowing.",
    source: "Abu Dawud 4:323",
    transliteration: "Bismillahilladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i wa huwas-sami'ul-'aleem",
    repeat: 3,
  },
  {
    id: "protection-92",
    category: "protection",
    title: "Last Two Verses of Surah al-Baqarah",
    arabic: "آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّن رُّسُلِهِ وَقَالُوا سَمِعْنَا وَأَطَعْنَا غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ",
    translation: "The Messenger has believed in what was revealed to him from his Lord, and so have the believers. All of them have believed in Allah and His angels and His books and His messengers: We make no distinction between any of His messengers. And they say, We hear and we obey. We seek Your forgiveness, our Lord, and to You is the final destination. (Quran 2:285-286)",
    source: "Quran 2:285-286, Sahih Al-Bukhari 5:345",
    transliteration: "Amanar-rasulu bima unzila ilayhi mir-rabbihi wal-mu'minun, kullun amana billahi wa mala'ikatihi wa kutubihi wa rusulihi, la nufarriqu bayna ahadin mir-rusulihi wa qalu sami'na wa ata'na ghufranaka rabbana wa ilaykal-masir",
    repeat: 1,
  },
  {
    id: "protection-93",
    category: "protection",
    title: "Protection from Dajjal",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ جَهَنَّمَ وَمِنْ عَذَابِ الْقَبْرِ وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ وَمِنْ شَرِّ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ",
    translation: "O Allah, I seek refuge in You from the punishment of Hell, from the punishment of the grave, from the trials of life and death, and from the evil of the trial of the False Messiah.",
    source: "Sahih Al-Bukhari 8:375, Sahih Muslim 1:587",
    transliteration: "Allahumma inni a'udhu bika min 'adhabi jahannam, wa min 'adhabul-qabr, wa min fitnatil-mahya wal-mamat, wa min sharri fitnatil-masihid-dajjal",
    repeat: 1,
  },
  {
    id: "dhikr-94",
    category: "dhikr",
    title: "SubhanAllah wa Bihamdihi x100",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    translation: "Glory be to Allah and all praise is His. (Whoever says this 100 times a day, all their sins will be forgiven even if they are as much as the foam of the sea.)",
    source: "Sahih Al-Bukhari 8:414, Sahih Muslim 4:2071",
    transliteration: "SubhanAllahi wa bihamdih",
    repeat: 100,
  },
  {
    id: "dhikr-95",
    category: "dhikr",
    title: "The Best Dhikr",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ",
    translation: "There is no deity worthy of worship except Allah. (The best dhikr is la ilaha illallah and the best dua is alhamdulillah.)",
    source: "At-Tirmidhi 5:462, Ibn Majah",
    transliteration: "La ilaha illallah",
    repeat: 1,
  },
  {
    id: "dhikr-96",
    category: "dhikr",
    title: "Salawat on the Prophet",
    arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ",
    translation: "O Allah, send blessings upon Muhammad and upon the family of Muhammad. (Whoever sends one salawat upon the Prophet, Allah sends ten blessings upon him.)",
    source: "Sahih Muslim 1:408, At-Tirmidhi 2:354",
    transliteration: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammad",
    repeat: 10,
  },
  {
    id: "dhikr-97",
    category: "dhikr",
    title: "Hasbiyallah",
    arabic: "حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
    translation: "Allah is sufficient for me. There is no deity worthy of worship except Him. I place my trust in Him and He is the Lord of the Great Throne. (Whoever says this 7 times morning and evening, Allah will take care of whatever worries him.)",
    source: "Abu Dawud 4:321",
    transliteration: "Hasbiyallahu la ilaha illa huwa 'alayhi tawakkaltu wa huwa Rabbul-'Arshil-'Adheem",
    repeat: 7,
  },
  {
    id: "dhikr-98",
    category: "dhikr",
    title: "SubhanAllahil Adheem wa Bihamdihi",
    arabic: "سُبْحَانَ اللَّهِ الْعَظِيمِ وَبِحَمْدِهِ",
    translation: "Glory be to Allah the Magnificent, and all praise is His. (Two words light on the tongue, heavy on the scales, beloved to the Most Merciful.)",
    source: "Sahih Al-Bukhari 8:417, Sahih Muslim 4:2072",
    transliteration: "SubhanAllahil-'Adheem wa bihamdih",
    repeat: 1,
  },
  {
    id: "dhikr-99",
    category: "dhikr",
    title: "Complete Tasbih, Tahmid, Takbir",
    arabic: "سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ",
    translation: "Glory be to Allah, all praise is due to Allah, there is no deity worthy of worship except Allah, and Allah is the Greatest.",
    source: "Sahih Muslim 4:2072",
    transliteration: "SubhanAllahi wal-hamdu lillahi wa la ilaha illallahu wallahu akbar",
    repeat: 1,
  },
  {
    id: "marriage-100",
    category: "marriage",
    title: "Dua on Seeing Spouse",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا وَخَيْرَ مَا جَبَلْتَهَا عَلَيْهِ وَأَعُوذُ بِكَ مِنْ شَرِّهَا وَشَرِّ مَا جَبَلْتَهَا عَلَيْهِ",
    translation: "O Allah, I ask You for her goodness and the goodness of the nature You have created in her, and I seek refuge in You from her evil and the evil of the nature You have created in her.",
    source: "Abu Dawud 2:248, Ibn Majah 1:617",
    transliteration: "Allahumma inni as'aluka khayrahā wa khayra ma jabaltaha 'alayhi wa a'udhu bika min sharriha wa sharri ma jabaltaha 'alayh",
    repeat: 1,
  },
  {
    id: "marriage-101",
    category: "marriage",
    title: "Dua Before Intercourse",
    arabic: "بِسْمِ اللَّهِ اللَّهُمَّ جَنِّبْنَا الشَّيْطَانَ وَجَنِّبِ الشَّيْطَانَ مَا رَزَقْتَنَا",
    translation: "In the name of Allah. O Allah, keep the devil away from us and keep the devil away from what You provide for us. (If a child is conceived, the devil will not harm it.)",
    source: "Sahih Al-Bukhari 7:94, Sahih Muslim 2:1058",
    transliteration: "Bismillah, Allahumma jannibnash-shaytana wa jannibish-shaytana ma razaqtana",
    repeat: 1,
  },
  {
    id: "marriage-102",
    category: "marriage",
    title: "Dua for a Righteous Spouse and Offspring",
    arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    translation: "Our Lord, grant us from among our spouses and offspring comfort to our eyes and make us a leader for the righteous.",
    source: "Quran 25:74",
    transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama",
    repeat: 1,
  },
  {
    id: "marriage-103",
    category: "marriage",
    title: "Dua at a Wedding",
    arabic: "بَارَكَ اللَّهُ لَكَ وَبَارَكَ عَلَيْكَ وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ",
    translation: "May Allah bless you, and shower His blessings upon you, and join you together in goodness.",
    source: "Abu Dawud 2:228, At-Tirmidhi 3:221",
    transliteration: "Barakallahu laka wa baraka 'alayka wa jama'a baynakuma fi khayr",
    repeat: 1,
  },
  {
    id: "hajj-104",
    category: "hajj",
    title: "Talbiyah",
    arabic: "لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ لَا شَرِيكَ لَكَ",
    translation: "Here I am O Allah, here I am. Here I am, You have no partner, here I am. Verily all praise, grace and sovereignty belong to You. You have no partner.",
    source: "Sahih Al-Bukhari 2:798, Sahih Muslim 2:841",
    transliteration: "Labbayk Allahumma labbayk, labbayk la shareeka laka labbayk, innal-hamda wan-ni'mata laka wal-mulk, la shareeka lak",
    repeat: 1,
  },
  {
    id: "hajj-105",
    category: "hajj",
    title: "Dua at the Ka'bah (Seeing the Ka'bah)",
    arabic: "اللَّهُمَّ زِدْ هَذَا الْبَيْتَ تَشْرِيفًا وَتَعْظِيمًا وَتَكْرِيمًا وَمَهَابَةً وَزِدْ مَنْ شَرَّفَهُ وَكَرَّمَهُ مِمَّنْ حَجَّهُ أَوِ اعْتَمَرَهُ تَشْرِيفًا وَتَكْرِيمًا وَتَعْظِيمًا وَبِرًّا",
    translation: "O Allah, increase this House in honour, esteem, respect and reverence, and increase those who honour and respect it — of those who perform Hajj or Umrah — in honour, esteem, reverence and righteousness.",
    source: "Al-Bayhaqi, Al-Azraqi",
    transliteration: "Allahumma zid hadhal-bayta tashrifan wa ta'dhiman wa takriman wa mahabatan wa zid man sharrafahu wa karramahu mimman hajjahu awi'tamarahu tashrifan wa takriman wa ta'dhiman wa birra",
    repeat: 1,
  },
  {
    id: "hajj-106",
    category: "hajj",
    title: "Dua at Safa and Marwa",
    arabic: "إِنَّ الصَّفَا وَالْمَرْوَةَ مِنْ شَعَائِرِ اللَّهِ نَبْدَأُ بِمَا بَدَأَ اللَّهُ بِهِ",
    translation: "Indeed, as-Safa and al-Marwa are among the symbols of Allah. We begin with what Allah began with.",
    source: "Sahih Muslim 2:888",
    transliteration: "Innas-safa wal-marwata min sha'a'irillah, nabda'u bima bada'allahu bih",
    repeat: 1,
  },
  {
    id: "hajj-107",
    category: "hajj",
    title: "Dua at Arafah",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    translation: "None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and all praise, and He is over all things omnipotent. (The best dua is the dua of the day of Arafah.)",
    source: "At-Tirmidhi 5:572",
    transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadir",
    repeat: 1,
  },
  {
    id: "grief-108",
    category: "grief",
    title: "Inna Lillahi (Upon a Calamity)",
    arabic: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ اللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا",
    translation: "Surely to Allah we belong and to Him we shall return. O Allah, reward me in my calamity and replace it with something better.",
    source: "Sahih Muslim 2:632",
    transliteration: "Inna lillahi wa inna ilayhi raji'un, Allahumma-jurni fi musibati wa akhlif li khayran minha",
    repeat: 1,
  },
  {
    id: "grief-109",
    category: "grief",
    title: "Dua for the Deceased",
    arabic: "اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ وَعَافِهِ وَاعْفُ عَنْهُ وَأَكْرِمْ نُزُلَهُ وَوَسِّعْ مُدْخَلَهُ وَاغْسِلْهُ بِالْمَاءِ وَالثَّلْجِ وَالْبَرَدِ",
    translation: "O Allah, forgive him and have mercy on him, keep him safe and sound and pardon him, honour the place where he settles, make his entrance wide, wash him with water, snow and hail.",
    source: "Sahih Muslim 2:663",
    transliteration: "Allahummaghfir lahu warhamhu wa 'afihi wa'fu 'anhu wa akrim nuzulahu wa wassi' mudkhalahu waghsilhu bil-ma'i wath-thalji wal-barad",
    repeat: 1,
  },
  {
    id: "grief-110",
    category: "grief",
    title: "Dua for Patience in Grief",
    arabic: "اللَّهُمَّ آجِرْنِي فِي مُصِيبَتِي وَأَعْقِبْنِي خَيْرًا مِنْهَا",
    translation: "O Allah, reward me for my affliction and compensate me with something better than it.",
    source: "Sahih Muslim 2:632",
    transliteration: "Allahumma ajirni fi musibati wa a'qibni khayran minha",
    repeat: 1,
  },
  {
    id: "grief-111",
    category: "grief",
    title: "Dua at the Graveside",
    arabic: "السَّلَامُ عَلَيْكُمْ أَهْلَ الدِّيَارِ مِنَ الْمُؤْمِنِينَ وَالْمُسْلِمِينَ وَيَرْحَمُ اللَّهُ الْمُسْتَقْدِمِينَ مِنَّا وَالْمُسْتَأْخِرِينَ وَإِنَّا إِنْ شَاءَ اللَّهُ بِكُمْ لَاحِقُونَ",
    translation: "Peace be upon you, O people of the dwellings, from among the believers and Muslims. May Allah have mercy on those who have gone ahead of us and those who are to follow, and verily, if Allah wills, we will join you.",
    source: "Sahih Muslim 2:671",
    transliteration: "As-salamu 'alaykum ahlad-diyari minal-mu'minina wal-muslimeen, wa yarhamullahul-mustaqdimiena minna wal-musta'khireen, wa inna insha'allahu bikum lahiqun",
    repeat: 1,
  },
  {
    id: "children-112",
    category: "children",
    title: "Dua for Newborn Protection",
    arabic: "أُعِيذُكَ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ",
    translation: "I seek refuge for you in the perfect words of Allah from every devil and every poisonous reptile and from every evil eye.",
    source: "Sahih Al-Bukhari 4:119",
    transliteration: "U'idhuka bikalimatillahit-tammati min kulli shaytanin wa hammatin wa min kulli 'aynin lammah",
    repeat: 1,
  },
  {
    id: "children-113",
    category: "children",
    title: "Dua for Righteous Children",
    arabic: "رَبِّ هَبْ لِي مِنْ لَدُنْكَ ذُرِّيَّةً طَيِّبَةً إِنَّكَ سَمِيعُ الدُّعَاءِ",
    translation: "My Lord, grant me from Yourself a good offspring. Indeed, You are the Hearer of supplication.",
    source: "Quran 3:38",
    transliteration: "Rabbi hab li min ladunka dhurriyyatan tayyibatan innaka sami'ud-du'a",
    repeat: 1,
  },
  {
    id: "children-114",
    category: "children",
    title: "Dua of Prophet Ibrahim for His Offspring",
    arabic: "رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِنْ ذُرِّيَّتِي رَبَّنَا وَتَقَبَّلْ دُعَاءِ",
    translation: "My Lord, make me an establisher of prayer, and from my descendants. Our Lord, and accept my supplication.",
    source: "Quran 14:40",
    transliteration: "Rabbij'alni muqimas-salati wa min dhurriyyati, rabbana wa taqabbal du'a",
    repeat: 1,
  },
  {
    id: "children-115",
    category: "children",
    title: "Dua Upon Seeing a Newborn",
    arabic: "بَارَكَ اللَّهُ لَكَ فِي الْمَوْهُوبِ لَكَ وَشَكَرْتَ الْوَاهِبَ وَبَلَغَ أَشُدَّهُ وَرُزِقْتَ بِرَّهُ",
    translation: "May Allah bless you in what has been gifted to you, may you give thanks to the Giver, may he reach maturity, and may you be granted his piety.",
    source: "Ibn As-Sunni, Al-Bayhaqi",
    transliteration: "Barakallahu laka fil-mawhubu laka wa shakarta-l-wahiba wa balagha ashuddahu wa ruziqta birrah",
    repeat: 1,
  },
  {
    id: "business-116",
    category: "business",
    title: "Dua for Provision (Rizq)",
    arabic: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
    translation: "O Allah, suffice me with what You have made lawful against what You have made unlawful, and make me independent of all others besides You through Your bounty.",
    source: "At-Tirmidhi 5:560",
    transliteration: "Allahummak-fini bihalali 'an haramika wa aghnini bifadlika 'amman siwak",
    repeat: 1,
  },
  {
    id: "business-117",
    category: "business",
    title: "Dua for Paying Off Debt",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ",
    translation: "O Allah, I seek refuge in You from anxiety and grief, from helplessness and laziness, from cowardice and miserliness, and from being overwhelmed by debt and subjugated by people.",
    source: "Sahih Al-Bukhari 7:158",
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazani wa a'udhu bika minal-'ajzi wal-kasali wa a'udhu bika minal-jubni wal-bukhli wa a'udhu bika min ghalabatid-dayni wa qahrir-rijal",
    repeat: 1,
  },
  {
    id: "business-118",
    category: "business",
    title: "Dua for Barakah in Wealth",
    arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيمَا رَزَقْتَنَا وَقِنَا عَذَابَ النَّارِ",
    translation: "O Allah, bless us in what You have provided for us and protect us from the punishment of the Fire.",
    source: "Ibn As-Sunni",
    transliteration: "Allahumma barik lana fima razaqtana wa qina 'adhaban-nar",
    repeat: 1,
  },
  {
    id: "business-119",
    category: "business",
    title: "Dua at the Market",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ يُحْيِي وَيُمِيتُ وَهُوَ حَيٌّ لَا يَمُوتُ بِيَدِهِ الْخَيْرُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    translation: "None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and all praise. He gives life and causes death. He is living and does not die. In His hand is all goodness and He is over all things omnipotent. (Allah will write a million good deeds for whoever says this at the market.)",
    source: "At-Tirmidhi 5:491",
    transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamdu yuhyi wa yumitu wa huwa hayyun la yamutu biyadihil-khayru wa huwa 'ala kulli shay'in qadir",
    repeat: 1,
  },
  {
    id: "nightPrayer-120",
    category: "nightPrayer",
    title: "Dua at Tahajjud",
    arabic: "اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ نُورُ السَّمَوَاتِ وَالْأَرْضِ وَمَنْ فِيهِنَّ وَلَكَ الْحَمْدُ أَنْتَ قَيِّمُ السَّمَوَاتِ وَالْأَرْضِ وَمَنْ فِيهِنَّ",
    translation: "O Allah, all praise is due to You. You are the Light of the heavens and the earth and whoever is in them. All praise is due to You. You are the Sustainer of the heavens and the earth and whoever is in them.",
    source: "Sahih Al-Bukhari 2:324, Sahih Muslim 1:769",
    transliteration: "Allahumma lakal-hamdu anta nurus-samawati wal-ardi wa man fihinn, wa lakal-hamdu anta qayyimus-samawati wal-ardi wa man fihinn",
    repeat: 1,
  },
  {
    id: "nightPrayer-121",
    category: "nightPrayer",
    title: "Witr Qunut",
    arabic: "اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ وَعَافِنِي فِيمَنْ عَافَيْتَ وَتَوَلَّنِي فِيمَنْ تَوَلَّيْتَ وَبَارِكْ لِي فِيمَا أَعْطَيْتَ وَقِنِي شَرَّ مَا قَضَيْتَ",
    translation: "O Allah, guide me along with those whom You have guided, pardon me along with those whom You have pardoned, be an ally to me along with those whom You are an ally to, and bless me in what You have given me, and protect me from the evil of what You have decreed.",
    source: "Abu Dawud 2:39, At-Tirmidhi 1:464",
    transliteration: "Allahummahdini fiman hadayt, wa 'afini fiman 'afayt, wa tawallani fiman tawallayt, wa barik li fima a'tayt, wa qini sharra ma qadayt",
    repeat: 1,
  },
  {
    id: "nightPrayer-122",
    category: "nightPrayer",
    title: "Dua for Laylat al-Qadr",
    arabic: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي",
    translation: "O Allah, You are Pardoning and You love to pardon, so pardon me.",
    source: "At-Tirmidhi 5:534, Ibn Majah 2:1265",
    transliteration: "Allahumma innaka 'afuwwun tuhibbul-'afwa fa'fu 'anni",
    repeat: 1,
  },
  {
    id: "nightPrayer-123",
    category: "nightPrayer",
    title: "Opening of Tahajjud Prayer",
    arabic: "اللَّهُمَّ رَبَّ جِبْرَائِيلَ وَمِيكَائِيلَ وَإِسْرَافِيلَ فَاطِرَ السَّمَوَاتِ وَالْأَرْضِ عَالِمَ الْغَيْبِ وَالشَّهَادَةِ أَنْتَ تَحْكُمُ بَيْنَ عِبَادِكَ فِيمَا كَانُوا فِيهِ يَخْتَلِفُونَ",
    translation: "O Allah, Lord of Jibreel, Mikail and Israfeel, Creator of the heavens and the earth, Knower of the unseen and the seen. You judge between Your servants in matters in which they differed.",
    source: "Sahih Muslim 1:770",
    transliteration: "Allahumma Rabba Jibra'ila wa Mika'ila wa Israfila, Fatiras-samawati wal-ardi, 'alimal-ghaybi wash-shahadati, anta tahkumu bayna 'ibadika fima kanu fihi yakhtalifun",
    repeat: 1,
  },
  {
    id: "quran-124",
    category: "quran",
    title: "Before Reciting the Quran",
    arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
    translation: "I seek refuge in Allah from the accursed devil.",
    source: "Quran 16:98",
    transliteration: "A'udhu billahi minash-shaytanir-rajeem",
    repeat: 1,
  },
  {
    id: "quran-125",
    category: "quran",
    title: "Al-Fatiha (Opening Chapter)",
    arabic: "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ الرَّحْمَنِ الرَّحِيمِ مَالِكِ يَوْمِ الدِّينِ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
    translation: "In the name of Allah, the Entirely Merciful, the Especially Merciful. All praise is due to Allah, Lord of the worlds — the Entirely Merciful, the Especially Merciful, Sovereign of the Day of Recompense. It is You we worship and You we ask for help. Guide us to the straight path — the path of those upon whom You have bestowed favour, not of those who have evoked anger or of those who are astray.",
    source: "Quran 1:1-7",
    transliteration: "Bismillahir-Rahmanir-Rahim, Alhamdu lillahi Rabbil-'alamin, Ar-Rahmanir-Rahim, Maliki yawmid-din, Iyyaka na'budu wa iyyaka nasta'in, Ihdinas-siratal-mustaqim, Siratal-ladhina an'amta 'alayhim, ghayril-maghdubi 'alayhim wa lad-dallin",
    repeat: 1,
  },
  {
    id: "quran-126",
    category: "quran",
    title: "Dua Upon Completing the Quran",
    arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ",
    translation: "Glory be to You O Allah and all praise, I bear witness that there is no deity worthy of worship except You. I seek Your forgiveness and I repent to You.",
    source: "An-Nasai, At-Tirmidhi",
    transliteration: "SubhanakaAllahumma wa bihamdika ash-hadu an la ilaha illa anta astaghfiruka wa atubu ilayk",
    repeat: 1,
  },
];
